version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: your-app-container
    ports:
      - "3000:3000" # Maps container's port 3000 to host's port 3000
    environment:
      NODE_ENV: production
    entrypoint: ["/app/docker/custom-entrypoint.sh"]
    volumes:
      - .:/app
    restart: unless-stopped